### ISSUE TITLE
Permissions error on ThinkPad t480s

### ISSUE THREAD

**Issue by decentralion** [haikarainen/light#34] opened 2018-05-20 18:11 UTC
I'm running a new ThinkPad T480s. Light is failing with the following issue:

```
❯ ./light -S 10 -v 2                                                                                                                                                              warning: "could not open '/sys/class/backlight/intel_backlight/brightness' for writing", in "src/helpers.c" on line 189.
warning: "check if this file exists or if you have the right permissions", in "src/helpers.c" on line 189.
warning: "could not open controller brightness file for writing, so controller is not accessible", in "src/light.c" on line 787.
warning: "controller not accessible", in "src/light.c" on line 906.
error: "could not find an accessible controller", in "src/light.c" on line 914.
error: "could not find suitable controller", in "src/light.c" on line 332.
error: "Initialization failed", in "src/main.c" on line 13.
```
`/sys/class/backlight/intel_backlight/brightness` does exist and contain a brightness value, so it looks like the problem is that light can't get permissions.

**Comment by haikarainen** [comment] 2018-06-06 08:09
You need to make sure you have the correct permissions, read the readme or contact the package maintainer

**Comment by troglobit** [comment] 2018-08-06 06:06
@decentralion I'm closing this, the problem is that you need the SUID root bit to be set, which is done at install.

**Closed by troglobit** 2018-08-06 06:06 UTC
