### ISSUE TITLE
Setting/adding/subtracting brightness does not work

### ISSUE THREAD

**Issue by Igetin** [haikarainen/light#8] opened 2016-01-09 15:54 UTC
Hello, I have a problem adjusting my laptop's brightness. I previously tried out [Xbacklight](https://github.com/tcatm/xbacklight), but it didn't work for me. So I installed Light.

The installation went without problems. The commands are "working", not a single error:

![terminal](http://i.imgur.com/CuaXcVY.png)

The thing is that my screen's brightness just **does not change** even though no errors are returned. My laptop is using the **radeon_bl0** controller.

There are three backlight-related plain text files in my /sys/class/backlight/radeon_bl0:
* actual_brightness
* brightness
* max_brightness, value is 255

The values of `actual_brightness` and `brightness` actually **do change** after adjusting the brightness with Light, but my screen just isn't affected by it. I have also rebooted my laptop several times, without luck.

I would appreciate any suggestions!

**Comment by haikarainen** [comment] 2016-01-13 12:21
Try to write directly to the controllers (bypassing light completely):

    sudo tee /sys/class/backlight/radeon_b10/brightness <<< 127
    sudo tee /sys/class/backlight/radeon_b10/brightness <<< 92
    sudo tee /sys/class/backlight/radeon_b10/brightness <<< 220

If that changes your actual screen brightness, the problem is my application. Otherwise the problem is your controller. I'd suggest applying some google-fu to this issue if that is the case.

**Comment by haikarainen** [comment] 2016-01-26 08:53
Closing this as I highly suspect this is a problem with your system (and not light itself).

**Closed by haikarainen** 2016-01-26 08:53 UTC

**Comment by Igetin** [comment] 2016-01-26 10:12
Sorry, I totally forgot to answer earlier.

So yeah, it certainly seems to be an issue with my drivers, as writing the brightness values directly does not work. I read that switching from the open-source radeon driver to the propietary Catalyst driver would fix the issue, but at the same time Catalyst is not (yet) supported in Fedora 23, which I'm using. Thus, downgrading to 22 would seem to be the best choice for now.
